dev_volumes:
  image: debian
  volumes:
    - debian_home:/home
    - $PWD/data:/data

java_dev:
  image: mikeascott/java-dev
  volumes_from:
    - dev_volumes
  ports:
    - "5901:5901"
#  command: /bin/bash /root/start-xrdp.sh
  links:
    - dev_volumes
